/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AlCom_constants.h"

namespace AlCom {

const AlComConstants g_AlCom_constants;

AlComConstants::AlComConstants() {
}

} // namespace

