/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AlCom_CONSTANTS_H
#define AlCom_CONSTANTS_H

#include "AlCom_types.h"

namespace AlCom {

class AlComConstants {
 public:
  AlComConstants();

};

extern const AlComConstants g_AlCom_constants;

} // namespace

#endif
