/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace AlCom {


SimpleRequest::~SimpleRequest() throw() {
}


void SimpleRequest::__set_interID(const InterID val) {
  this->interID = val;
}

void SimpleRequest::__set_state(const bool val) {
  this->state = val;
}

uint32_t SimpleRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->interID);
          this->__isset.interID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->state);
          this->__isset.state = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SimpleRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SimpleRequest");

  xfer += oprot->writeFieldBegin("interID", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->interID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("state", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->state);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SimpleRequest &a, SimpleRequest &b) {
  using ::std::swap;
  swap(a.interID, b.interID);
  swap(a.state, b.state);
  swap(a.__isset, b.__isset);
}

SimpleRequest::SimpleRequest(const SimpleRequest& other0) {
  interID = other0.interID;
  state = other0.state;
  __isset = other0.__isset;
}
SimpleRequest& SimpleRequest::operator=(const SimpleRequest& other1) {
  interID = other1.interID;
  state = other1.state;
  __isset = other1.__isset;
  return *this;
}
void SimpleRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SimpleRequest(";
  out << "interID=" << to_string(interID);
  out << ", " << "state=" << to_string(state);
  out << ")";
}

} // namespace
